import { Theme } from "../theme.slint";

export component CustomLineEdit inherits Rectangle {
    in property <string> placeholder-text: "";
    in-out property <string> text: input.text;
    
    height: 36px;
    background: Theme.surface.darker(0.2);
    border-radius: 4px;
    border-width: 1px;
    border-color: input.has-focus ? Theme.primary : Theme.border;

    input := TextInput {
        x: Theme.spacing-small;
        y: (parent.height - self.height) / 2;
        width: parent.width - Theme.spacing-small * 2;
        color: Theme.text;
        font-size: Theme.font-size-regular;
        single-line: true;
    }

    Text {
        x: Theme.spacing-small;
        y: (parent.height - self.height) / 2;
        text: root.placeholder-text;
        color: Theme.text-secondary;
        font-size: Theme.font-size-regular;
        visible: input.text == "" && !input.has-focus;
    }
}
