[workspace]
publish = false
git_release_enable = false
git_tag_enable = false

[[package]]
name = "widget-core"

[[package]]
name = "widget-ui"

[[package]]
name = "sticky_plugin"

[[package]]
name = "todo_plugin"

[[package]]
name = "widget-cli"

# Configure the main app crate to hold the unified changelog and handle the actual release
[[package]]
name = "widget-rs"
git_release_enable = true
git_tag_enable = true
changelog_path = "../../CHANGELOG.md"
changelog_include = ["widget-core", "widget-ui", "sticky_plugin", "todo_plugin", "widget-cli"]
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"
