[package]
name = "widget-cli"
version.workspace = true
edition.workspace = true
description = "Widget plugin/core"
repository.workspace = true
authors.workspace = true
license.workspace = true

[package.metadata.wix]
upgrade-guid = "4920E300-33BB-4F15-B5E3-A5B2EE2D50E9"
path-guid = "FAD0CD1B-9A4B-4E90-B8A2-E3F45344391F"
license = false
eula = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
toml_edit = "0.22"
