[package]
name = "widget-cli"
version = "0.1.0"
edition = "2021"
description = "CLI tool for managing widget-rs plugins."
repository = "https://github.com/tierlabx/widget-rs.git"
authors = ["tierlabx"]
license = "MIT"

[package.metadata.wix]
upgrade-guid = "4920E300-33BB-4F15-B5E3-A5B2EE2D50E9"
path-guid = "FAD0CD1B-9A4B-4E90-B8A2-E3F45344391F"
license = false
eula = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
toml_edit = "0.22"
