use crate::layout::{page_header, settings_card, settings_row};
use gpui::*;

pub fn render_shortcuts_settings() -> Vec<gpui::AnyElement> {
    vec![
        div()
            .flex()
            .justify_between()
            .items_center()
            .w_full()
            .child(page_header("快捷键与指南", "查看操作快捷键与桌面交互技巧"))
            .into_any_element(),
        settings_card()
            .child(
                settings_row(true)
                    .child(
                        div()
                            .flex()
                            .flex_col()
                            .gap(px(4.0))
                            .child(
                                div()
                                    .text_base()
                                    .font_weight(FontWeight::SEMIBOLD)
                                    .text_color(rgb(0xf2f2f2))
                                    .child("排版与吸附模式"),
                            )
                            .child(
                                div()
                                    .text_sm()
                                    .text_color(rgb(0x8b949e))
                                    .child("在托盘图标或控制面板中开启排版模式后拖拽小部件"),
                            ),
                    )
                    .child(
                        div()
                            .px(px(10.0))
                            .py(px(4.0))
                            .bg(rgba(0xffffff0d))
                            .border_1()
                            .border_color(rgba(0xffffff1a))
                            .rounded(px(6.0))
                            .text_sm()
                            .font_weight(FontWeight::MEDIUM)
                            .text_color(rgb(0x00d992))
                            .child("支持多屏磁吸"),
                    ),
            )
            .child(
                settings_row(false)
                    .child(
                        div()
                            .flex()
                            .flex_col()
                            .gap(px(4.0))
                            .child(
                                div()
                                    .text_base()
                                    .font_weight(FontWeight::SEMIBOLD)
                                    .text_color(rgb(0xf2f2f2))
                                    .child("免打扰与鼠标穿透"),
                            )
                            .child(
                                div()
                                    .text_sm()
                                    .text_color(rgb(0x8b949e))
                                    .child("在小部件设置中可单独开启鼠标穿透与始终置顶"),
                            ),
                    )
                    .child(
                        div()
                            .px(px(10.0))
                            .py(px(4.0))
                            .bg(rgba(0xffffff0d))
                            .border_1()
                            .border_color(rgba(0xffffff1a))
                            .rounded(px(6.0))
                            .text_sm()
                            .font_weight(FontWeight::MEDIUM)
                            .text_color(rgb(0x8b949e))
                            .child("原生级穿透"),
                    ),
            )
            .into_any_element(),
    ]
}
