[package]
name = "widget-rs"
version = "0.1.4"
edition = "2021"
repository = "https://github.com/tierlabx/widget-rs.git"
authors = ["tierlabx"]
license = "MIT"
description = "A lightweight desktop widget platform based on Rust and GPUI."

[package.metadata.wix]
upgrade-guid = "F4306D34-5A01-4EF2-B092-8734E92C6396"
path-guid = "86135684-15A6-4DF1-862E-FB93B28A682D"
license = false
eula = false

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
mimalloc = { version = "0.1", default-features = false }
sticky_plugin.workspace = true
todo_plugin.workspace = true
widget-core.workspace = true
widget-ui.workspace = true

anyhow = "1.0"
directories.workspace = true
gpui-component-assets = "0.5.1"
image.workspace = true
raw-window-handle.workspace = true
rust-embed = "8.5"
serde.workspace = true
serde_json.workspace = true
tao.workspace = true
tray-icon.workspace = true
windows-sys.workspace = true
winreg = "0.56.0"

[build-dependencies]
winres.workspace = true

[package.metadata.packager]
identifier = "com.tierlabx.widget-rs"
publisher = "tierlabx"
before-packaging-command = "cargo build --release"
formats = ["nsis", "msi", "dmg", "app", "deb", "appimage"]

[package.metadata.packager.windows]
# Add shortcuts for windows installer
nsis = { create-desktop-shortcut = true, create-start-menu-shortcut = true }
