export global Theme {
    out property <color> background: #050507;
    out property <color> surface: #101010;
    out property <color> primary: #00d992;
    out property <color> border: #3d3a39;
    out property <color> text: #ffffff;
    out property <color> text-secondary: #888888;
    out property <color> sticky-background: #151515ee; // Dark translucent
    out property <color> sticky-text: #e0e0e0;
    
    // Typography
    out property <length> font-size-small: 12px;
    out property <length> font-size-regular: 14px;
    out property <length> font-size-large: 18px;
    out property <length> font-size-title: 24px;
    
    // Spacing
    out property <length> spacing-small: 8px;
    out property <length> spacing-regular: 16px;
    out property <length> spacing-large: 24px;
}
