[package]
name = "stretchly_plugin"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
raw-window-handle.workspace = true
widget-core.workspace = true
windows-sys = { workspace = true, features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_HiDpi",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

