name: Release Packager

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-and-package:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        
      - name: Install cargo-packager
        run: cargo install cargo-packager --locked

      - name: Install WiX Toolset
        run: |
          dotnet tool install --global wix --version 4.*
          wix extension add WixToolset.UI.wixext
          wix extension add WixToolset.Util.wixext
        
      - name: Package Application
        run: cargo packager --release -f nsis -f wix

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.target }}
          path: |
            target/release/*-setup.exe
            target/release/*.msi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            target/release/*-setup.exe
            target/release/*.msi

